// generated by wof/tools/make_proto_assets.py - do not edit
#pragma once

// per-map values (LEVEL_W, MAP_CELLS, HOME_X, DECK_X0/1, c_map, ...) come from map_<x>.dat at run time
#define MAX_LEVEL_W 30576
#define MAX_MAP_CELLS 3565
#define MAX_HUTS 14
#define MAX_BUNKERS 13
#define MAX_PILLBOXES 30
#define MAX_FLAGS 5
#define MAX_LSO 2
#define MAP_LETTERS "abcdefghijklmno"
#define LEVEL_H 576
#define VIEW_H 240
#define PF_H 163
#define SEP_H 8
#define BASE_ROW 299		// image row of world y = 0
#define WATER_ROW 288
#define MARGIN 1024
#define PL_AX 64
#define PL_AY 24
#define WH_AX 62
#define WH_AY 12
#define LIVE_H 336		// camera limit; rows below hold the wrecked-hut tiles
#define BAND_ROW 21		// source band (BAND_ROWS tile rows): 1/8 view, bob, waves, wrecked huts
#define BAND_ROWS 15
#define WRECK_DST_ROW 17
#define WRECK_SRC_ROW 21
#define WRECK_ROWS 4
#define MINI_ROW 336		// image row of the 1/8 view (MINI_H rows)
#define MINI_H 176
#define MINI_SEA 144
#define MINI_X0 208
#define MI_AX 16
#define MI_AY 8
#define MINI_FRAMES 40
#define MINI_SHEET_ROWS 4
#define MINI_PLANE_N0 40
#define MINI_WRECK_DST_ROW 29
#define MINI_WRECK_SRC_ROW 32
#define MINI_WRECK_ROWS 2
static const u8 c_fr_mini[32] =
{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 16, 17, 17, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 24, 24,
};
static const u8 c_fr_minifx[35] =
{
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 255, 255, 255, 255,
	36, 37, 255, 255, 255, 255, 255, 255, 255,
};
static const u16 c_night_pal[16] =
{
	0, 0, 2019, 1977, 2489, 3112, 2723, 26, 1100, 150, 291, 827, 554, 2450, 1646, 18,
};
#define WAVE_DST_ROW 18
#define WAVE_SRC_ROW 21
#define WAVE_PHASES 12
#define WAVE_PERIOD 6
#define PILL_ROW 17
#define PILL_COLS 3
#define BOB_DST_ROW 10
#define BOB_ROWS 8
#define BOB_COLS 49
#define BOB_SRC_ROW 21
#define SO_AX 24
#define SO_AY 10
static const u8 c_fr_minisold[2] =
{
	38, 39,
};
#define WP_AX 48
#define WP_AY 40
#define WP_FR_RC 0
#define WP_FR_RO 20
#define WP_FR_TOR 40
#define WP_FR_SELT 42
#define WP_FR_ROW 43
#define WP_FRAMES 46
#define WP_ROWS 6
#define ZP_AX 56
#define ZP_AY 24
#define ZP_FRAMES 26
#define ZP_ROWS 4
#define ZM_FRAMES 16
#define ZM_ROWS 2
static const u8 c_fr_zero[56] =
{
	0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 7, 7, 7, 8, 8, 2, 2, 2, 1, 1, 1, 9, 10,
	11, 12, 12, 12, 13, 13, 13, 14, 14, 15, 15, 15, 6, 6, 5, 16, 16, 16, 17, 17, 13, 13, 13, 12, 12, 12, 18, 19,
};
static const u8 c_fr_zmini[56] =
{
	0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 7, 7, 7, 8, 8, 2, 2, 2, 1, 1, 1, 0, 0,
	9, 10, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13, 6, 6, 5, 14, 14, 14, 15, 15, 11, 11, 11, 10, 10, 10, 9, 9,
};
#define ZP_FR_FC10 20
#define ZP_FR_FD10 21
#define ZP_FR_FC1A 22
#define ZP_FR_FD1A 23
#define ZP_FR_PARK1 24
#define ZP_FR_PARK2 25
#define GUN_FR_MINI 14
#define GN_AX 32
#define GN_AY 24
#define AA_TAB_PRE 24
#define AA_TAB_LEN 320
static const s8 c_aa_tab[320] =
{
	24, 16, 8, 0, 0, 1, 0, 2, 2, 3, 3, 3, 1, 2, 3, 3, 0, 1, 2, 3, 0, 1, 2, 3,
	0, 0, 0, 3, 3, 6, 6, 6, 0, 1, 1, 3, 3, 5, 5, 6, 1, 1, 2, 3, 3, 4, 5, 5,
	1, 2, 2, 3, 3, 4, 4, 5, 2, 2, 3, 3, 3, 3, 4, 4, 1, 2, 3, 2, 1, 2, 3, 2,
	1, 3, 2, 1, 0, -112, -112, -112, -112, -112, -112, -112, -112, -112, -112, -112, -112, -104, -103, -102, -101, -100, -99, -98,
	-99, -100, -101, -102, -103, -112, -111, -110, -109, -108, -107, -106, -107, -108, -109, -110, -111, -104, -104, -104, -104, -104, -104, -104,
	-104, -104, -104, -104, -104, -113, -105, -112, -111, -110, -109, -108, -107, -106, -104, -103, -102, -101, -100, -99, -98, -108, -100, -112,
	-111, -110, -109, -108, -107, -106, -107, -108, -109, -110, -111, -104, -103, -102, -101, -100, -99, -98, -99, -100, -101, -102, -103, 0,
	0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
};
#define FX_AX 20
#define FX_AY 22
#define FX_BOMB0 0
#define FX_EXP0 12
#define FX_SPL0 18
#define FX_RIC0 25
#define FX_SMK0 26
#define FX_BAL0 32
#define FX_FRAMES 35

static const s32 c_sin16[92] =
{
	0, 4572, 4572, 4572, 4572, 5712, 6850, 7987,
	9121, 10252, 11380, 12505, 13626, 14742, 15854, 16962,
	18064, 19161, 20252, 21337, 22415, 23486, 24550, 25607,
	26656, 27697, 28729, 29753, 30767, 31773, 32768, 33754,
	34729, 35694, 36647, 37590, 38521, 39441, 40348, 41243,
	42126, 42996, 43852, 44696, 45525, 46341, 47143, 47930,
	48702, 49461, 50203, 50931, 51643, 52340, 53020, 53684,
	54332, 54963, 55578, 56175, 56756, 57319, 57865, 58393,
	58903, 59396, 59870, 60326, 60764, 61183, 61584, 61966,
	62329, 62672, 62997, 63303, 63590, 63856, 64104, 64332,
	64541, 64729, 64898, 65048, 65177, 65286, 65376, 65446,
	65496, 65526, 65536, 1,
};
static const s32 c_turncos16[28] =
{
	65536, 64225, 62259, 59638, 56361, 53084, 49152, 45875, 39322,
	32768, 26214, 19661, 15073, 13107, 0, 3277, 16384, 29491,
	39322, 45875, 49152, 53084, 56361, 59638, 62259, 64225, 0,
	4572,
};
static const s16 c_objh[6] =
{
	36, 35, 35, 9, 13, 12,
};
static const s16 c_tantab[256] =
{
	1, 1, 3, 4, 6, 7, 9, 11, 12, 14, 15, 17, 18, 20, 22, 23,
	25, 26, 28, 29, 31, 33, 34, 36, 37, 39, 41, 42, 44, 46, 47, 49,
	50, 52, 54, 55, 57, 59, 60, 62, 64, 65, 67, 69, 70, 72, 74, 75,
	77, 79, 81, 82, 84, 86, 88, 89, 91, 93, 95, 96, 98, 100, 102, 104,
	106, 107, 109, 111, 113, 115, 117, 119, 121, 123, 124, 126, 128, 130, 132, 134,
	136, 138, 140, 142, 145, 147, 149, 151, 153, 155, 157, 159, 162, 164, 166, 168,
	171, 173, 175, 177, 180, 182, 185, 187, 189, 192, 194, 197, 199, 202, 204, 207,
	210, 212, 215, 218, 220, 223, 226, 229, 232, 234, 237, 240, 243, 246, 249, 252,
	255, 259, 262, 265, 268, 272, 275, 278, 282, 285, 289, 293, 296, 300, 304, 308,
	311, 315, 319, 323, 328, 332, 336, 340, 345, 349, 354, 358, 363, 368, 373, 378,
	383, 388, 393, 398, 404, 409, 415, 421, 427, 433, 439, 445, 451, 458, 465, 471,
	478, 486, 493, 500, 508, 516, 524, 532, 541, 549, 558, 568, 577, 587, 597, 607,
	618, 628, 640, 651, 663, 675, 688, 701, 715, 729, 744, 759, 774, 791, 808, 825,
	843, 862, 882, 903, 925, 947, 971, 996, 1022, 1049, 1077, 1108, 1140, 1173, 1209, 1246,
	1286, 1329, 1374, 1423, 1475, 1531, 1591, 1655, 1725, 1801, 1884, 1975, 2075, 2185, 2308, 2445,
	2599, 2773, 2972, 3202, 3470, 3787, 4166, 4631, 5210, 5956, 6950, 8341, 10428, 13905, 20859, -23816,
};
static const u8 c_frameno[20] =
{
	10, 10, 9, 9, 8, 8, 7, 7, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1, 1,
};
static const s16 c_clr[12] =
{
	2, 12, 10, 6, 4, 2, 5, 7, 9, 12, 14, 5,
};
static const s16 c_gear[12] =
{
	5, 4, 3, 3, 3, 5, 3, 2, 1, 0, 0, 10,
};
static const s16 c_turnclr[6] =
{
	2, 2, 4, 6, 10, 11,
};
static const u8 c_fr_pitch_l[20] =
{
	0, 0, 1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9,
};
static const u8 c_fr_pitch_r[20] =
{
	10, 10, 11, 11, 12, 12, 13, 13, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19,
};
static const u8 c_fr_loop_l[26] =
{
	20, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 30, 31, 31, 32, 33, 34, 35, 25, 24, 23, 22, 21, 20,
};
static const u8 c_fr_loop_r[26] =
{
	15, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 31, 31, 31, 30, 30, 46, 47, 48, 49, 41, 40, 39, 38, 37, 36,
};
static const u8 c_fr_deck_l[8] =
{
	50, 51, 52, 53, 54, 55, 56, 57,
};
static const u8 c_fr_deck_r[8] =
{
	58, 59, 60, 61, 62, 63, 64, 65,
};
static const u8 c_fr_wheel_l[20] =
{
	0, 0, 1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9,
};
static const u8 c_fr_wheel_r[20] =
{
	10, 10, 11, 11, 12, 12, 13, 13, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19,
};
#define FR_CRASH_L 66
#define FR_CRASH_R 67
static const u8 c_fr_torp[108] =
{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 255, 255, 255,
	255, 255, 255, 23, 24, 25, 26, 255, 255, 255, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
	43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255,
};
#define TORP_FRAMES 57
#define TORP_SHEET_ROWS 6
#define TP_AX 60
#define EL_AX 28
#define EL_AY 0
static const u8 c_fr_flash_a_l[11] =
{
	0, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
};
static const u8 c_fr_flash_a_r[11] =
{
	0, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
};
static const u8 c_fr_flash_b_l[11] =
{
	0, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
};
static const u8 c_fr_flash_b_r[11] =
{
	0, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
};
#define CR_AX 17
#define CR_AY 45
#define HUD_DIGIT0 0
#define HUD_ROPE1 10
#define HUD_BOMB 26
#define PLANE_FRAMES 108
#define WHEEL_FRAMES 20
#define PLANE_SHEET_COLS 10
#define PLANE_SHEET_ROWS 11
#define WHEEL_SHEET_COLS 10
#define WHEEL_SHEET_ROWS 2

