#!/usr/bin/env python3
"""Copy the muzzle-flash frames out of game/source_assets/hellcat.png into flash.png (own EMX sheet).
The flash must not share the hellcat's IMSPR asset: AGT crashes when IMSPR and EMX entities mix in a layer.
Writes game/flash_data.h with FLASH_FR0 (first flash frame in the hellcat sheet).
Usage: make_flash_sheet.py <game dir>"""
import re, sys, os
from PIL import Image

game = sys.argv[1]
hdr = open(os.path.join(game, 'flight_data.h')).read()
fr = []
for nm in ('c_fr_flash_a_l', 'c_fr_flash_a_r', 'c_fr_flash_b_l', 'c_fr_flash_b_r'):
    body = re.search(nm + r'\[\d+\]\s*=\s*\{([^}]*)\}', hdr).group(1)
    fr += [int(v, 0) for v in body.replace('\n', ' ').split(',') if v.strip()][1:]   # [0] is unused
fr0, fr1 = min(fr), max(fr) + 1
src = Image.open(os.path.join(game, 'source_assets', 'hellcat.png'))
cw, ch, cols = 128, 48, 10
n = fr1 - fr0
rows = (n + cols - 1) // cols
dst = Image.new('P', (cw * cols, ch * rows), 0)
dst.putpalette(src.getpalette())
for i in range(n):
    s = fr0 + i
    cell = src.crop(((s % cols) * cw, (s // cols) * ch, (s % cols + 1) * cw, (s // cols + 1) * ch))
    dst.paste(cell, ((i % cols) * cw, (i // cols) * ch))
dst.save(os.path.join(game, 'source_assets', 'flash.png'))
with open(os.path.join(game, 'flash_data.h'), 'w') as f:
    f.write('// generated by tools/make_flash_sheet.py - do not edit\n')
    f.write(f'#define FLASH_FR0 {fr0}\n#define FLASH_FRAMES {n}\n#define FLASH_SHEET_ROWS {rows}\n')
print('flash frames', fr0, '..', fr1 - 1, '->', n, 'frames,', rows, 'rows')
