#!/usr/bin/env python3
"""Convert the Amiga game samples (raw signed 8-bit) for the STE DMA mixer (game/snd.h).

All samples keep their native data (52 KB; resampling the low-rate ones up to the output rate would cost ~90 KB);
the mixer steps through them at rate = PAL_CLOCK / period (16.16 step = SND_STEP_K / period). Each use (sample +
Amiga period, render_sound.md 6.3) is a SND_ id with its default period.
Writes game/snd_data.h.
Usage: make_sounds.py <game dir> [rate]
"""
import os, sys

ROOT = os.path.join(os.path.dirname(__file__), '..')
SOUNDS = os.path.join(ROOT, 'amiga-original/sounds')
PAL_CLOCK = 3546895

# id, file, Amiga period (None = native, pitched at run time), comment
VARIANTS = [
    ('GUN',         'machinegun',    200, 'player machine gun, ch0 prio, loop'),
    ('GUN_ENEMY',   'machinegun',    160, 'enemy machine gun, ch1 prio, loop'),
    ('GUN_AA',      'machinegun',    320, 'AA gun fire, ch3 prio, loop'),
    ('BOOM',        'boom',          500, 'impact on land, ch2 prio, once'),
    ('SPLASH',      'splash',        350, 'impact on water, ch2, once'),
    ('SPLASH_LOOP', 'splash',        800, 'ch2 loop while G_252e4 == 1'),
    ('SCREECH',     'screech',       350, 'deck touch-down / hook, ch3, once'),
    ('SCREAM',      'scream',        380, 'soldier hit, ch3, once'),
    ('CLANG',       'metal.clang.1', 450, 'crash, ch3, once'),
    ('GRIND',       'grind.1',       450, 'ch3 loop while G_252e4 is 2 or 3'),
    ('ENGINE',      'engine',        None, 'player/enemy engine, native data, pitched at run time'),
]


# sample -> log2 of the oversampling factor (the mixer shifts the step by it). The result must stay below 32768
# bytes: the mixer indexes with a signed word (a long index read garbage: the engine turned into noise)
OVERSAMPLE = {}


def s8(b):
    return b - 256 if b > 127 else b


def resample(data, src_rate, dst_rate):
    n = max(1, int(len(data) * dst_rate / src_rate))
    out = []
    for i in range(n):
        p = i * src_rate / dst_rate
        k = int(p); f = p - k
        a = data[k]; b = data[k + 1] if k + 1 < len(data) else data[k]
        out.append(int(round(a + (b - a) * f)))
    return out


def main(game, rate=12517):
    lines = ['// generated by wof/tools/make_sounds.py - do not edit', '#pragma once', '',
             f'#define SND_RATE {rate}',
             f'#define SND_STEP_K {round(PAL_CLOCK * 65536 / rate)}UL\t// 16.16 step = SND_STEP_K / amiga_period', '']
    files = []
    total = 0
    for fn in dict.fromkeys(f for _, f, _, _ in VARIANTS):
        data = [s8(b) for b in open(os.path.join(SOUNDS, fn), 'rb').read()]
        if fn in OVERSAMPLE:
            # the mixer picks the nearest sample: at a step that is no simple ratio this adds a hiss only ~15 dB
            # under the engine. Stored 2x oversampled (linear, wrapping at the loop) the error drops to ~-21 dB.
            k, n = 1 << OVERSAMPLE[fn], len(data)
            data = [int(round(data[i] + (data[(i + 1) % n] - data[i]) * j / k)) for i in range(n) for j in range(k)]
        cname = 'c_smp_' + fn.replace('.', '_')
        body = ',\n'.join('\t' + ','.join(str(v) for v in data[j:j + 24]) for j in range(0, len(data), 24))
        assert len(data) < 32768, fn
        lines.append(f'static const s8 {cname}[{len(data)}] =\n{{\n{body}\n}};')
        files.append((fn, cname, len(data)))
        total += len(data)
    byname = {fn: (c, n) for fn, c, n in files}
    for i, (sid, fn, period, comment) in enumerate(VARIANTS):
        lines.append(f'#define SND_{sid} {i}\t// {fn}, period {period or "dynamic"}: {comment}')
    lines.append(f'#define SND_COUNT {len(VARIANTS)}')
    lines.append('static const s8 * const c_snd_data[SND_COUNT] = { ' + ', '.join(byname[f][0] for _, f, _, _ in VARIANTS) + ' };')
    lines.append('static const u16 c_snd_len[SND_COUNT] = { ' + ', '.join(str(byname[f][1]) for _, f, _, _ in VARIANTS) + ' };')
    lines.append('static const u8 c_snd_shift[SND_COUNT] = { ' + ', '.join(str(OVERSAMPLE.get(f, 0)) for _, f, _, _ in VARIANTS) + ' };\t// log2 oversampling of the stored data')
    lines.append('static const u16 c_snd_period[SND_COUNT] = { ' + ', '.join(str(p or 808) for _, _, p, _ in VARIANTS) + ' };')
    open(os.path.join(game, 'snd_data.h'), 'w').write('\n'.join(lines) + '\n')
    print(f'{len(VARIANTS)} sounds from {len(files)} samples, {total} bytes, output {rate} Hz')


if __name__ == '__main__':
    main(sys.argv[1], int(sys.argv[2]) if len(sys.argv) > 2 else 12517)
